### ISSUE TITLE
Curve EQ is not working in Glyphs

### ISSUE THREAD

**Issue by Nevu** [jenskutilek/Curve-Equalizer#1]
hello,

it seems that the eq doesnt work in g2.

all gui started, but nothing happens?
also in output panel no errors. mmh

**Comment by zar-nicolas20** [comment]
I was report the same issue. Seems that @mekkablue is working in something.

**Comment by jenskutilek** [comment]
I started porting the Curve EQ from RoboFont to Glyphs together with Georg, but then completely forgot about it ... it doesn’t actually do anything yet except showing the window, sorry ...

**Comment by jenskutilek** [comment]
Finally, I implemented Curve Equalizer for Glyphs 3. You can find and install it in the plugin manager.
