### ISSUE TITLE
Reproducible settings

### ISSUE THREAD

**Issue by nicksherman** [jenskutilek/Curve-Equalizer#14]
First, I'd like to say how much I like Curve Equalizer. I use it all the time. Thanks for making it!

In the more recent versions though, I miss the option to set the value via radio buttons. Not necessarily because I love radio buttons (though they did work well, and that was the setting I used most), but more because it was a quick and reliable way to return the tool to a value I had used before. With the current slider interface it's much trickier to match a previous setting.

If you didn't want to re-introduce the radio button interface, maybe you could at least explicitly show the current value of the slider? It would be slightly more fussy than the radio buttons, but would at least make it easier to match previous settings with more accuracy.

**Comment by jenskutilek** [comment]
I was trying to de-clutter the interface, and practically never using the radio buttons myself, I got rid of them. Good to hear that they are being used, though. I will bring them back :)

**Comment by jenskutilek** [comment]
I finally found some time to work on this again, and brought back the previous EQ options.
