### ISSUE TITLE
Extension non-responsive in RF 4.5b

### ISSUE THREAD

**Issue by jeremymickel** [jenskutilek/Curve-Equalizer#16]
Tried using this extension recently, and all the options are grayed out in RF. No tracebacks.

<img width="251" alt="image" src="https://github.com/jenskutilek/Curve-Equalizer/assets/2964496/56450433-4ef7-4c27-9b9f-333aad8f4896">

**Comment by jeremymickel** [comment]
Ha just kidding, it seems to be working.

**Comment by jenskutilek** [comment]
Maybe related to https://github.com/jenskutilek/Curve-Equalizer/issues/13 ... sometimes to activate the UI, it needs a click another window, then in the glyph window again.
