### ISSUE TITLE
Curve Equalizer and mixed component glyphs

### ISSUE THREAD

**Issue by arialcrime** [jenskutilek/Curve-Equalizer#5]
Hey there,

In Robofont 3, I found that Curve EQ is not working on outlines in glyphs where there is also a component present.  It also is not showing the preview outline.

Am I doing something completely wrong here?

**Comment by jenskutilek** [comment]
I think it never worked correctly on mixed composites … I will have a look.

**Comment by jenskutilek** [comment]
Thank you for your patience @arialcrime ;) v2.1.3 can finally handle glyphs with components and outlines.
